services:
  _defaults:
    autoconfigure: true
    public: false
    autowire: true

  Rinsvent\Data2DTOBundle\Service\ServiceResolver:
    bind:
      $transformerLocator: !tagged_locator { tag: 'rinsvent.transformer', index_by: 'key', default_index_method: 'getLocatorKey' }

  _instanceof:
    Rinsvent\Data2DTOBundle\Service\AbstractTransformer:
      tags: [ 'rinsvent.transformer' ]
